version: '2'

services:
  web:
    build: .
    image: aqt01/flask   
    expose:
      - "5000"
    volumes:
      - .:/usr/src/app
    networks:
      - "flask"
    command: python ./app.py

  server:
    build:
      dockerfile: Dockerfile.caddy 
    image: aqt01/flask-server 
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/Caddyfile
    networks:
      - "flask"
    environment:
      DOMAIN_NAME: '127.0.0.1' 
      FLASK_PORT: 5000

networks:
  "flask":
