apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
      - env:
        - name: DOMAIN_NAME
          value: 127.0.0.1
        - name: FLASK_PORT
          value: "5000"
        image: abiosoft/caddy
        name: server
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /etc/Caddyfile
          name: server-claim0
      restartPolicy: Always
      volumes:
      - name: server-claim0
        persistentVolumeClaim:
          claimName: server-claim0
status: {}
